# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/traffic-infra',
                'doc_host': 'https://traffic-kowshik.github.io',
                'git_url': 'https://github.com/traffic-kowshik/traffic-infra',
                'lib_path': 'traffic_infra'},
  'syms': {'traffic_infra.core': {'traffic_infra.core.foo': ('core.html#foo', 'traffic_infra/core.py')}}}
